[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "grand-slam"
version = "0.1.0"
dependencies = ["Pillow>=10.0.1,<12.0.0", "tzlocal"]


[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points.'bullpen.mlbled.plugin']
"grand_slam" = "grand_slam:load"

[tool.black]
line-length = 120
